In [9]:
0b0111

7

In [8]:
0x03

3

In [10]:
import numpy as np

In [16]:
x = np.arange(12, dtype=np.uint64)
x, x.dtype

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=uint64),
 dtype('uint64'))

In [17]:
with open("data.dat", "wb") as f:
    f.write(x.tobytes())

In [19]:
dat = x.tobytes()
dat

b'\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00'

In [27]:
from scipy import io

In [28]:
io.savemat('data.mat', {'data': x})

In [24]:
np.frombuffer(dat, dtype=np.int64)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
data = np.load('data.npz')
data

NpzFile 'data.npz' with keys: x, y, z

In [33]:
data['y']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=uint64)

In [ ]:
np.savez_compressed()

In [1]:
import numpy as np

In [2]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])